#include "landmarks.h"

Landmark landmarks[LANDMARK_COUNT] = {
    {"Drottningholm palace", 10, 36},
    {"Birka", 10, 36},
    {"Gamla Stan", 11, 36},
    {"Medieval walls of Visby", 11, 42},
    {"Tyresta National Park", 11, 36},
    {"Sandhamn island", 12, 36},
    {"Gripsholm castle", 9, 36},
    {"Sigtuna", 10, 35},
    {"Uppsala cathedral", 10, 34},
    {"Treriksröset (the tripoint where Sweden, Norway and Finland meet)", 15, 0},
    {"Kebnekaise (Sweden's tallest mountain)", 11, 4},
    {"Kiruna", 14, 4},
    {"Gammelstad Church Town", 17, 13},
    {"Åre", 3, 22},
    {"Lake Storsjön (location of the legendary monster Storsjöodjuret)", 5, 23},
    {"Sundsvall", 9, 25},
    {"Falun copper mine", 7, 32},
    {"Örebro Castle", 6, 36},
    {"Liseberg amusement park", 1, 41},
    {"Läckö Castle", 4, 38},
    {"Vadstena Castle", 6, 39},
    {"Turning Torso", 3, 47},
    {"Öresund Bridge", 2, 46},
    {"Kullen Lighthouse", 2, 45},
    {"Ales Stenar", 4, 47},
    {"Varnhem Abbey Ruins", 4, 39},
    {"Kalmar castle", 7, 44},
    {"Tanum rock carvings", 0, 38},
    {"Fårö island", 12, 41},
    {"Kungliga Tekniska högskolan", 11, 36},
    {"Gustavianum", 10, 34},
    {"Skuleberget (world's highest coastline)", 11, 23},
    {"Lund cathedral", 3, 46},
    {"Karlstad", 3, 36},
    {"Sofiero Palace", 2, 45},
    {"Borgholm Castle", 8, 43},
    {"Icehotel in Jukkasjärvi", 15, 4},
    {"Abisko National Park", 12, 2}
};